### ISSUE TITLE
Trouble compiling under GCC and Clang

### ISSUE THREAD

**Issue by fosskers** [jb55/viscal#1]
I'm on Arch, where a plain `make` defaults to GCC. This errors out with:

```
colin@yumi ~/c/c/viscal> make
cc -Wall -Wextra -O0 -Wno-unused-parameter -Werror=int-conversion -std=c99 -g `pkg-config --cflags --libs libical gtk+-3.0` -o viscal calendar.c
calendar.c:75:16: error: variably modified ‘events’ at file scope
   struct event events[MAX_EVENTS];
```
among a number of warnings.

Compiling instead with `env CC=clang make` gives (among the warnings):
```
/bin/ld: /tmp/calendar-dcd667.o: undefined reference to symbol 'round@@GLIBC_2.2.5'
/usr/lib/libm.so.6: error adding symbols: DSO missing from command line
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
```
It's not clear to me why `clang` would be having trouble finding `glibc`, which is definitely installed on my system.

I tried again in a docker container running Ubuntu 16.10 and got the same results.

Thoughts?

**Comment by jb55** [comment]
should work with gcc now

**Comment by jb55** [comment]
btw there's not much here yet.  as you can tell from me hardcoding calendar loads right now: https://github.com/jb55/viscal/blob/e34b5a50e96269fd0aac1cd17995b5a1776bb40c/calendar.c#L925

**Comment by fosskers** [comment]
Np, thanks for the fix.
